[package]
name = "env"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_env"
path = "env.rs"

[dependencies]
libc = "0.2.42"
uucore = "0.0.1"
rust-ini = "0.13.0"

[[bin]]
name = "env"
path = "../../uumain.rs"
